# Generated by Django 4.2.1 on 2023-05-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('phone_number', models.PositiveIntegerField()),
                ('descriptions', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
