# Generated by Django 4.2.2 on 2023-06-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categori_name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newimage/')),
                ('title', models.CharField(max_length=150)),
                ('discriptions', models.TextField()),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newcategori', to='myapp.newscategori')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
