# Generated by Django 4.2.2 on 2023-06-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categori_name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newimage/')),
                ('title', models.CharField(max_length=150)),
                ('discriptions', models.TextField()),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newabout', to='myapp.newscategori')),
            ],
        ),
    ]
