# Generated by Django 4.2.2 on 2023-06-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_newsabout_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='details',
            name='ctg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newabout', to='myapp.newsabout'),
        ),
    ]
