# Generated by Django 4.2.2 on 2023-06-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='details',
            name='ctg',
        ),
    ]
