# Generated by Django 4.2.2 on 2023-07-02 08:23

import autoslug.fields
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_info_options_remove_details_ctg'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdetails',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='newsdetails',
            name='discriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
